### ISSUE TITLE
Example site

### ISSUE THREAD

**Issue by NicoHood** [Zenithar/hugo-theme-bleak#44]
Hi,
it would be nice if you could add some example site. The one you made a screenshot in the readme, it would be nice to know how to reproduce the website.

I had problems to get the initial website running, as the config.toml was incomplete. I was missing the following settings:
```toml
theme = "hugo-theme-bleak"
baseurl = "http://website.de/"
languageCode = "de-de"
title = "Blog"
```

Now I try to write some posts, but I got the following problems:

* inserting images (where to place them, which format!?)
* "Posts" Entry, how to remove this?
* Setting "share" to false does not seem to work for me
* Setting "featured" to true makes the post disappear. I excepted it to become black!?
* It seems categories are not used for this theme, only tags?

A sample site would very likely solve most problems and answer questions.
